### ISSUE TITLE
DrawBufferBytes is incorrect in JS and not flexible in all languages

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/due-libraries#37]
Is this true?

DrawBuffer: Takes an array of size x*y of colors int
DrawBufferBytes Takes an array of x*y*4 where each byte is R, G, B, A.
But the implementation is not correct. It works with JS canvas that returns 32K buffer but does not work with code below.

The implementation also assumes a 128x64 display. We are introduction color 160x120 display support. This implementation needs to be clarified and adjusted on all languages.

```
let BrainPad = new due.DUELinkController(new SerialUSB());
await BrainPad.Connect();

let frameBuffer = new Uint32Array(128*64); 
function SetPixel(color, x, y){
    if(x<0 || x>127 || y<0 || y>63) return;
    let index = y * 128 + x;
    frameBuffer[index] = color;
}
function Clear(color){
    frameBuffer.fill(color);
}
async function Show()
{
    //await BrainPad.Display.DrawBufferBytes(frameBuffer);
    await BrainPad.Display.DrawBuffer(frameBuffer);
}

Clear(0);
while(true){
    var x = Math.random()*127;
    var y = Math.random()*63;
    SetPixel(200, x, y);
    await Show();
}
```

**Comment by gus-ghielec** [comment]
These pages need to be updated
https://www.brainpad.com/js-framebuffer/
https://www.brainpad.com/framebuffer/

**Comment by Palomino34** [comment]
DrawBuffer: Takes an array of size xy of colors int
DrawBufferBytes Takes an array of xy*4 where each byte is R, G, B, A.

They are true.

**Comment by gus-ghielec** [comment]
We should charge this to DrawBuffer(colorDepth, data) the data will always be 5:6:5 and the colorDepth determine how is the data sent to the device, 4bpp for example.

DUE lcdStream() needs to be changed to take an argument, which is color depth. Then it internally converted the incoming data to the display's native format, let's say 5:6:5 for example.

This allows the PC coffee to be uniform and gives the user there option to lose color depth in exchange of higher speeds.

**Comment by taylorza** [comment]
I think we need to enhance the I2C and SPI internal interface. Right now we are filling an entire buffer on the device before we send it to the display, then we copy it to another buffer (we can save 1K RAM here if we fix this). 

On SC007, we will only be able to stream 1 bit images because we do not have enough memory to create a buffer for 4 and 8 bit color. 

If we can stream directly from serial to I2C or SPI then we would not care how big the buffer needs to be, we only need enough for 1 pixel so that we can convert it.

**Comment by gus-ghielec** [comment]
I thought 1bpp is all we need for sc007.

**Comment by Palomino34** [comment]
I thought 32bit RGB is much easier for users instead of 5:6:5, and this was the reason we choose 32bit data.
