### ISSUE TITLE
Print and println should support bool

### ISSUE THREAD

**Issue by gus-ghielec** [ghi-electronics/due-libraries#39]
In this example, a bool is returned and the println should print 0 or 1. This is to keep it inline of how DUE works

https://www.brainpad.com/lessons/touch/

**Comment by taylorza** [comment]
Fixed for .NET, Python and JavaScript libraries in commit [ca243ef](https://github.com/ghi-electronics/due-libraries/commit/ca243ef4af7e67dad4d304923a44f63becffa928)
