### ISSUE TITLE
Buttons Enable & WasPressed Functions

### ISSUE THREAD

**Issue by ammaralnatour** [ghi-electronics/due-libraries#42]
We need to change the if conditions to the same conditions inside IsReleased function

**Comment by gus-ghielec** [comment]
Please add the fixed code

**Comment by ammaralnatour** [comment]
async Enable(pin, enable) {
        if (pin !== 97 && pin !== 98 && pin !== 65 && pin !== 66 && pin !== 0 && pin !== 1 && pin !== 2 && pin !== 'A' && pin !== 'B' && pin !== 'a' && pin !== 'b') {
            throw new Error("Invalid pin.");
        }

        const cmd = `btnenable(${pin}, ${Number(enable)})`;

        await this.serialPort.WriteCommand(cmd);
        const res = await this.serialPort.ReadResponse();

        return res.success;
    }

    async WasPressed(pin) {
        if (pin !== 97 && pin !== 98 && pin !== 65 && pin !== 66 && pin !== 0 && pin !== 1 && pin !== 2 && pin !== 'A' && pin !== 'B' && pin !== 'a' && pin !== 'b') {
            throw new Error("Invalid pin.");
        }

        const cmd = `print(btndown(${pin}))`;

        await this.serialPort.WriteCommand(cmd);
        const res = await this.serialPort.ReadResponse();

        if (res.success) {
            try {
                return parseInt(res.response) === 1;
            } catch {
                console.log("Press EXCEPTION");
            }
        }

        console.log("Press ERROR");
        return false;
    }

**Comment by ammaralnatour** [comment]
async Enable(pin, enable) {
        if (pin !== 97 && pin !== 98 && pin !== 65 && pin !== 66 && pin !== 0 && pin !== 1 && pin !== 2 && pin !== 'A' && pin !== 'B' && pin !== 'a' && pin !== 'b') {
            throw new Error("Invalid pin.");
        }

        const cmd = `btnenable(${pin}, ${Number(enable)})`;

        await this.serialPort.WriteCommand(cmd);
        const res = await this.serialPort.ReadResponse();

        return res.success;
    }

    async WasPressed(pin) {
        if (pin !== 97 && pin !== 98 && pin !== 65 && pin !== 66 && pin !== 0 && pin !== 1 && pin !== 2 && pin !== 'A' && pin !== 'B' && pin !== 'a' && pin !== 'b') {
            throw new Error("Invalid pin.");
        }

        const cmd = `print(btndown(${pin}))`;

        await this.serialPort.WriteCommand(cmd);
        const res = await this.serialPort.ReadResponse();

        if (res.success) {
            try {
                return parseInt(res.response) === 1;
            } catch {
                console.log("Press EXCEPTION");
            }
        }

        console.log("Press ERROR");
        return false;
    }

**Comment by gus-ghielec** [comment]
@taylorza I would also review the entire functionality and names. Is? Was?... Just to make sure all make sense

**Comment by taylorza** [comment]
@gus-ghielec Typically, these functions would be `JustPressed` and `JustReleased` in game engines. Would you like to go with that terminology?

**Comment by gus-ghielec** [comment]
Sounds good. But now we also need to modify the DUE firmware to match the names... And update docs

**Comment by taylorza** [comment]
The pin checks for the ButtonController have been made consisted across all the language libraries. And the functions have been renamed as follows

`WasPressed` => `JustPressed`
`IsReleased` => `JustReleased`
